### ISSUE TITLE
Databases aren't getting attached

### ISSUE THREAD

**Issue by monsieur-d** [Sitecore/Sitecore-Instance-Manager#157]
**Importance:**  
FYI (I only wanted to let you know)

**Valid for QA**  
I hereby confirm the issue is (only) reproducible on the latest QA version 1.5.0.40
which was downloaded today from http://dl.sitecore.net/updater/qa/sim

**Description:**  
If I add an new instance of Sitecore 8.2u2 the databases won't be attached by the SIM-Tool (with Sql-Server 2012). With the latest stable version 1.5.0.2 it does work properly.

**Scenario:**  
Add a new SC 82u2 instance. But I don't know if this issue is anyhow dependant on the SC-version. I haven't tried it with any other version.

**Attachments:**  
Please find attached latest log files from this folders:
```
%APPDATA%\..\Roaming\Sitecore\Sitecore Instance Manager-QA\logs 
```
[2017-04-18.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/929912/2017-04-18.txt)

**Comment by AlenPelin** [comment]
Seems to be caused by this:
http://stackoverflow.com/questions/32648654/publishing-website-error-this-access-control-list-is-not-in-canonical-form-and

**Comment by AlenPelin** [comment]
@monsieur-d could you try to apply the solution in this article to confirm that's the case?

**Comment by AlenPelin** [comment]
The issue should be fixed now, could you confirm?

**Comment by monsieur-d** [comment]
@AlenPelin unfortunately it still does not work with the new version (1.5.0.41). 
The solution from stackoverflow you posted above does not work in this case since I can't reorder the permissions after the site is added to IIS but before the SIM tool tries to attach the databases. I even tried to reorder the permissions and then reinstall the instance but this didn't work either. The databases weren't attached and the permissions were ordered incorrectly again. So I think if this is in fact the problem, the SIM tool should do that action.
I've attached you again the logs from my tests with the new SIM version.
[2017-04-20.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/941698/2017-04-20.txt)

**Comment by AlenPelin** [comment]
Should be fixed by 363d19b

**Comment by monsieur-d** [comment]
Indeed it is. It works again now. Thank you!

**Comment by AlenPelin** [comment]
Thanks for confirmation.
