### ISSUE TITLE
Unable to build: failed to restore version '1.0.0.15' of package 'Sitecore.Diagnostics.Logging'

### ISSUE THREAD

**Issue by chenhendrawan** [Sitecore/Sitecore-Instance-Manager#34]
The build is failed because NuGet failed to restore non existing version of a package. It looks for version 1.0.0.15, while I can only found version 1.0.0.12 in NuGet public repository https://www.nuget.org/packages/Sitecore.Diagnostics.Logging/

**Comment by AlenPelin** [comment]
Thanks for reporting the issue, it should have already been fixed now.

**Comment by chenhendrawan** [comment]
Still failed for other package
NuGet Package restore failed for project SIM.Tool: Unable to find version '1.0.0.14' of package 'Sitecore.Diagnostics.Logging.Log4Net'..
Thanks for quick response, anyway.

**Comment by AlenPelin** [comment]
Did you checkout latest version? It should use Sitecore.Diagnostics.Logging.Log4Net 1.0.0.15

**Comment by chenhendrawan** [comment]
Ah ok it works now. Great. Thanks.
